defaults: &defaults
  adapter: mysql2
  encoding: utf8
  username: root
  #password:
  host: localhost
  #socket: /var/run/mysqld/mysqld.sock

development:
  <<: *defaults
  database: hwt

production:
  <<: *defaults
  database: hwt_prod

test:
  <<: *defaults
  database: hwt_test
